language: python
python:
  - "2.6"
  - "2.7"
# run
install:
  - pip install -r tests/requirements.txt --use-mirrors
  - rvm use 1.9.3
  - gem install sass compass
  - nvm use 0.10
  - npm install coffee-script less stylus underscore
script:
 - django-admin.py test --settings=tests.settings -v 2 --with-spec -x